### ISSUE TITLE
Create turtle animation file

### ISSUE THREAD

**Issue by jonathandavidlewis** [Screwloose-Games/frozen-dungeon#4]
- [ ] idle (loop)
- [ ] death (no loop)
- [ ] attack (no loop)
- [ ] hide (no loop)
- [ ] walk (loop)

**Comment by Anticdope** [comment]
This was in the last PR. Uploaded before this ticket was made. I cant remember how aseprite and aseprite wizard handles looping in conjunction with one another. We need to sync on this. Also, why a death animation?
